Improvements to pages
Davigo-Studio/govigedit-docs pull request #2
Opened 2022-12-26 00:22 UTC by MN4444

gave community resources more resources and updated getting started

2022-12-26 01:18 UTC, MN4444 commented
i just want to mark this as ready

2022-12-26 01:19 UTC, MN4444 commented
oh now i understand

2022-12-26 12:05 UTC, SquirrelKiev requested changes

2022-12-26 12:05 UTC, SquirrelKiev commented on docs/community.md
>  ## Video Tutorials
This line needs to be changed to make more sense

2022-12-26 12:05 UTC, SquirrelKiev commented on docs/getting-started.md
> +!> Don't make the killzone too small as this can lead to problems later down the line
beloved punctuation

2022-12-26 14:28 UTC, MN4444 commented on docs/community.md
>  ## Video Tutorials
what do you mean by that

2023-01-08 18:03 UTC, SquirrelKiev approved these changes

2023-01-08 18:03 UTC, merged